prose:
  rooturl: 'site/content'
  siteurl: 'https://auctioner-monkey-24535.netlify.com'
  media: 'site/static/img'
  ignore: 
    - .keep
  metadata:
    site/content/post:
      - name: 'description'
        field:
          element: 'text'
          label: "Description"
          placeholder: "Description"
          type: 'text'
          value: ''
      - name: 'date'
        field:
          element: 'text'
          label: "Date"
          placeholder: "Date"
          type: 'text'
          value: ''