prose:
  rooturl: 'site/content'
  siteurl: 'https://auctioner-monkey-24535.netlify.com'
  media: 'site/static/img'
  ignore: 
    - .keep
  metadata:
    post:
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          type: 'text'
      - name: 'description'
        field:
          element: 'text'
          label: 'Description'
          type: 'text'
      - name: 'date'
        field:
          element: 'text'
          label: 'Date'
          type: 'text'